# Generated by Django 2.1.7 on 2019-03-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sludge', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=25)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('author', models.CharField(max_length=15)),
            ],
        ),
    ]
