# Generated by Django 2.1.7 on 2019-03-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20190321_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogs',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
