# Generated by Django 2.1.7 on 2019-03-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20190322_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=100)),
                ('image_name', models.CharField(max_length=50)),
            ],
        ),
    ]
