# Generated by Django 2.1.7 on 2019-03-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allblogs',
            old_name='image',
            new_name='thumnail',
        ),
    ]
