# Generated by Django 2.1.7 on 2019-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20190329_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allblogs',
            name='sludge',
            field=models.CharField(max_length=100),
        ),
    ]
